### ISSUE TITLE
Segfault on start, I believe I know the problem

### ISSUE THREAD

**Issue by Phate6660** [mohanson/gameboy#18]
I'm currently running `bspwm`, and everything is set to tiling.

I believe the issue is that `gameboy` is trying to launch with specific geometry size, but since it can't due to tiling, it segfaults.

If I'm right, I can fix this by setting `bspwm` to float that window.

The problem though, is that I can't obtain the `wm_class` since the window instantly closes.

So could you tell me what the `wm_class` is?

**Comment by mohanson** [comment]
I haven't used `bspwm` so it is difficult for me to really understand your problem, but commenting out these lines may be useful, probably a problem with the GUI library ` minifb`.

https://github.com/mohanson/gameboy/blob/master/src/main.rs#L31-L37

**Comment by Phate6660** [comment]
Simply changing `option.resize` to `false` did the trick.

Thanks for the help.
